from enum import Enum


class EstadoJob(Enum):
    NAO_INICIADO = "NAO INICIADO"
    ESPERANDO = "ESPERANDO"
    EXECUTANDO = "EXECUTANDO"
    DELETANDO = "DELETANDO"
    ERRO = "ERRO"
    CONCLUIDO = "CONCLUIDO"
